export const products = [
    { id: '1', name: 'MEXICAN FURY', price: 9.99, image: require('./assets/product-placeholder.png') },
    { id: '2', name: 'FIERY GAZPACHO', price: 8.99, image: require('./assets/product-placeholder.png') },
    { id: '3', name: 'HEAVENLY HARISSA', price: 10.99, image: require('./assets/product-placeholder.png') },
    { id: '4', name: 'JAMAICAN JERK', price: 9.49, image: require('./assets/product-placeholder.png') },
    { id: '5', name: 'REGAL RED PEPPER', price: 7.99, image: require('./assets/product-placeholder.png') },
    { id: '6', name: 'TOTALLY THAI', price: 8.49, image: require('./assets/product-placeholder.png') },
    { id: '7', name: 'SCORCHING SRIRACHA', price: 11.99, image: require('./assets/product-placeholder.png') },
    { id: '8', name: 'GHOST PEPPER BLAST', price: 14.99, image: require('./assets/product-placeholder.png') },
    { id: '9', name: 'CAJUN KICK', price: 9.99, image: require('./assets/product-placeholder.png') },
    { id: '10', name: 'HABANERO HEAT', price: 12.99, image: require('./assets/product-placeholder.png') },
    { id: '11', name: 'CHIPOTLE CHARM', price: 10.49, image: require('./assets/product-placeholder.png') },
    { id: '12', name: 'MANGO TANGO', price: 8.99, image: require('./assets/product-placeholder.png') },
    { id: '13', name: 'GARLIC INFERNO', price: 9.99, image: require('./assets/product-placeholder.png') },
    { id: '14', name: 'WASABI WILDFIRE', price: 13.99, image: require('./assets/product-placeholder.png') },
    { id: '15', name: 'CAROLINA REAPER RAGE', price: 15.99, image: require('./assets/product-placeholder.png') },
    { id: '16', name: 'JALAPENO JUBILEE', price: 7.99, image: require('./assets/product-placeholder.png') },
    { id: '17', name: 'SCOTCH BONNET SIZZLE', price: 11.49, image: require('./assets/product-placeholder.png') },
    { id: '18', name: 'PERI-PERI PUNCH', price: 10.99, image: require('./assets/product-placeholder.png') },
    { id: '19', name: 'TABASCO TORNADO', price: 8.99, image: require('./assets/product-placeholder.png') },
    { id: '20', name: 'GOCHUJANG GUSTO', price: 12.49, image: require('./assets/product-placeholder.png') },
];